[agents.pandora]
template = "agents/pandora.md"
includes.replace = ["common/base.md", "common/hitl.md"]
appends.replace = []


[agents.toil]
template = "agents/toil.md"
includes.replace = ["common/base.md", "common/afk.md"]
appends.replace = []


[agents.greed]
template = "agents/greed.md"
includes.replace = ["common/base.md", "common/hitl.md"]
appends.replace = []


[agents.war]
template = "agents/war.md"
includes.replace = ["common/base.md", "common/afk.md"]
appends.replace = []


[agents.envy]
template = "agents/envy.md"
includes.replace = ["common/base.md", "common/afk.md"]
appends.replace = []

